import os
import ycm_core
from clang_helpers import PrepareClangFlags


SEARCH_LIMIT = 21

cpp_include_template = '/usr/include/c++/{}'
x86_64_include_template = '/usr/include/x86_64-linux-gnu/c++/{}'
lib_x86_64_include_template = '/usr/lib/gcc/x86_64-linux-gnu/{}/include/'
backward_include_template = '/usr/include/c++/{}/backward'
llvm_template_with_dot = '/usr/lib/llvm-{}.{}/lib/clang/'
llvm_template_without_dot = '/usr/lib/llvm-{}/lib/clang/'
clang_template = '{}.{}.{}/include'

def fill_line_once(line):
    response = None
    for version in range(SEARCH_LIMIT):
        filled = line.format(version)
        if os.path.exists(filled):
            response = filled
    if response is None:
        resposne = ""
    return response

def fill_clang_line_with_dot(llvm_template, clang_template):
    response = None
    for major in range(SEARCH_LIMIT):
        for minor in range(SEARCH_LIMIT):
            llvm_path = llvm_template.format(major, minor)
            if os.path.exists(llvm_path):
                for suffix in range(SEARCH_LIMIT):
                    clang_path = llvm_path + clang_template.format(major, minor, suffix)
                    if os.path.exists(clang_path):
                        response = clang_path
    return response

def fill_clang_line_without_dot(llvm_template, clang_template):
    response = None
    for major in range(SEARCH_LIMIT):
        llvm_path = llvm_template.format(major)
        if os.path.exists(llvm_path):
            for minor in range(SEARCH_LIMIT):
                for suffix in range(SEARCH_LIMIT):
                    clang_path = llvm_path + clang_template.format(major, minor, suffix)
                    if os.path.exists(clang_path):
                        response = clang_path
    return response


cpp_include_line = fill_line_once(cpp_include_template)
x86_64_include_line = fill_line_once(x86_64_include_template)
lib_x86_64_include_line = fill_line_once(lib_x86_64_include_template)
backward_include_line = fill_line_once(backward_include_template)
clang_include_line = fill_clang_line_with_dot(llvm_template_with_dot, clang_template)
if clang_include_line is None:
    clang_include_line = fill_clang_line_without_dot(llvm_template_without_dot, clang_template)


flags = [
    '-Wall',
    '-Wextra',
    '-std=c++20',
    '-cc1',
    '-triple',
    '-Woverflow',
    '-ftrapv',
    '-x',
    'c++',
    '-pthread',
    '-stdlib=libc++',
    '-isystem',
    '/usr/local/include',
    '-isystem',
    cpp_include_line,
    '-isystem',
    x86_64_include_line,
    '-isystem',
    lib_x86_64_include_line,
    '-isystem',
    backward_include_line,
    '-isystem',
    clang_include_line,
    '-isystem',
    '/usr/include/x86_64-linux-gnu',
    '-isystem',
    '/usr/include',
    '-isystem',
    '/usr/local/include/coin-or',
    '-isystem',
    '/usr/include/coin',
    '-isystem',
]


compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh', '.cpp', '.c', '' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

    # NOTE: This is just for YouCompleteMe; it's highly likely that your project
    # does NOT need to remove the stdlib flag. DO NOT USE THIS IN YOUR
    # ycm_extra_conf IF YOU'RE NOT 100% SURE YOU NEED IT.
    try:
      final_flags.remove( '-stdlib=libc++' )
    except ValueError:
      pass
  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }
